apiVersion: execution.securecodebox.io/v1
kind: Scan
metadata:
  generateName: "semgrep-mi-app-"
  namespace: scb
spec:
  scanType: "semgrep"
  parameters:
    - "--config=p/ci"
    - "."
  volumes:
    - name: source
      emptyDir: {}
  initContainers:
    - name: clone-repo
      image: alpine/git
      command:
        - /bin/sh
        - -c
        - |
          echo "Clonando repositorio..."
          git clone https://gitlab.com/ahmedpuco03/mi-app-vulnerable.git /src
      volumeMounts:
        - name: source
          mountPath: /src
  volumeMounts:
    - name: source
      mountPath: /src
  hookSelector:
    matchLabels:
      defectdojo.securecodebox.io/enabled: "true"
  env:
    - name: "DEFECTDOJO_PRODUCT_NAME"
      value: "mi-app-vulnerable1"
    - name: "DEFECTDOJO_PRODUCT_TYPE_NAME"
      value: "USFQ-Apps"
    - name: "DEFECTDOJO_TOOL_CONFIGURATION_ID"
      value: "2"
    - name: "DEFECTDOJO_PRODUCT_ID"
      value: "8"
    - name: "DEFECTDOJO_ENGAGEMENT_ID"
      value: "38"