apiVersion: execution.securecodebox.io/v1
kind: Scan
metadata:
  generateName: "semgrep-mi-app-"
  namespace: scb
spec:
  scanType: "semgrep"
  parameters:
    - "--config=p/ci"
    - "."  # analizará el código clonado aquí
  volumes:
    - name: source
      emptyDir: {}
  initContainers:
    - name: clone-repo
      image: alpine/git
      command:
        - /bin/sh
        - -c
        - |
          echo "Clonando repositorio..."
          git clone https://gitlab.com/ahmedpuco03/mi-app-vulnerable.git /src
      volumeMounts:
        - name: source
          mountPath: /src
  volumeMounts:
    - name: source
      mountPath: /src
