apiVersion: "execution.securecodebox.io/v1"
kind: Scan
metadata:
  generateName: "semgrep-mi-app-"
  namespace: scb
spec:
  scanType: "semgrep"

  parameters:
    - "--config=p/ci"
    - "."
    - "https://gitlab.com/ahmedpuco03/mi-app-vulnerable.git"
    - "gitlab-scanner-credentials"  # debe existir en el namespace
