apiVersion: execution.securecodebox.io/v1
kind: Scan
metadata:
  generateName: "semgrep-mi-app-"
  namespace: scb
  # Las anotaciones pueden quedarse, pero el bloque 'persistence'
  # tendrá prioridad y es más confiable.
  annotations:
    defectdojo.securecodebox.io/product-name: "mi-app-vulnerable1" # <- Reemplaza con el nombre real
    defectdojo.securecodebox.io/product-type-name: "USFQ-Apps"
    defectdojo.securecodebox.io/tool-type-name: "Semgrep"
spec:
  scanType: "semgrep"
  parameters:
    - "--config=p/ci"
    - "."
  volumes:
    - name: source
      emptyDir: {}
  initContainers:
    - name: clone-repo
      image: alpine/git
      command:
        - /bin/sh
        - -c
        - |
          echo "Clonando repositorio..."
          git clone https://gitlab.com/ahmedpuco03/mi-app-vulnerable.git /src
      volumeMounts:
        - name: source
          mountPath: /src
  volumeMounts:
    - name: source
      mountPath: /src
  
  # --- INICIO DE LA CORRECCIÓN ---
  # Añade este bloque para controlar explícitamente la persistencia
  persistence:
    defectDojo:
      # Dile a SCB que use un producto que YA existe en DefectDojo.
      # (Debes crear este producto manualmente en la UI de DefectDojo
      #  y asignarle el ProductType "USFQ-Apps").
      product:
        # Usa el nombre exacto del producto en DefectDojo
        name: "mi-app-vulnerable1" 
        
      engagement:
        # Define cómo se llamará el 'Engagement' (la prueba)
        name: "Semgrep Scan (CI)"
        # Puedes usar variables de SCB para hacerlo dinámico
        # name: "Semgrep Scan - {{.spec.scanType}}-{{.metadata.name}}"
  # --- FIN DE LA CORRECCIÓN ---