apiVersion: execution.securecodebox.io/v1
kind: Scan
metadata:
  generateName: "semgrep-mi-app-"
  namespace: scb
  annotations:
    defectdojo.securecodebox.io/product-id: "8"           # Producto existente en DefectDojo
    defectdojo.securecodebox.io/product-type-id: "2"      # Tipo de producto (ID) correspondiente
    defectdojo.securecodebox.io/test-title: "Semgrep Scan mi-app-vulnerable"
    defectdojo.securecodebox.io/test-type: "SAST"
    defectdojo.securecodebox.io/environment: "Development"
spec:
  scanType: "semgrep"
  parameters:
    - "--config=p/ci"
    - "."
  volumes:
    - name: source
      emptyDir: {}
  initContainers:
    - name: clone-repo
      image: alpine/git
      command:
        - /bin/sh
        - -c
        - |
          echo "Clonando repositorio..."
          git clone https://gitlab.com/ahmedpuco03/mi-app-vulnerable.git /src
      volumeMounts:
        - name: source
          mountPath: /src
  volumeMounts:
    - name: source
      mountPath: /src
