apiVersion: execution.securecodebox.io/v1
kind: Scan
metadata:
  generateName: "semgrep-mi-app-"
  namespace: scb
  annotations:
    defectdojo.securecodebox.io/tool-configuration-id: 2
    defectdojo.securecodebox.io/product-id: 8
    defectdojo.securecodebox.io/engagement-id: 3
    defectdojo.securecodebox.io/test-type-id: 170
      
spec:
  scanType: "semgrep"
  parameters:
    - "--config=p/ci"
    - "/src"   # 🔥 Usa el directorio clonado

  volumes:
    - name: source
      emptyDir: {}

  initContainers:
    - name: clone-repo
      image: alpine/git
      command:
        - /bin/sh
        - -c
        - |
          echo "Clonando repositorio..."
          git clone https://gitlab.com/ahmedpuco03/mi-app-vulnerable.git /src
      volumeMounts:
        - name: source
          mountPath: /src

  volumeMounts:
    - name: source
      mountPath: /src   # 🔥 faltaba esto
