apiVersion: execution.securecodebox.io/v1
kind: Scan
metadata:
  generateName: "semgrep-mi-app-"
  namespace: scb
  # Las anotaciones pueden quedarse, pero el bloque 'persistence'
  # tendrá prioridad y es más confiable.
  annotations:
    defectdojo.securecodebox.io/product-id: "8"
    defectdojo.securecodebox.io/product-name: "mi-app-vulnerable1"
    defectdojo.securecodebox.io/product-type-name: "USFQ-Apps"
    defectdojo.securecodebox.io/tool-configuration-id: "2"
    defectdojo.securecodebox.io/engagement-id: "43"
    defectdojo.securecodebox.io/engagemente.name: "pruebas_semgrep"
    defectdojo.securecodebox.io/test-type: "Semgrep JSON Report"

spec:
  scanType: "semgrep"
  parameters:
    - "--config=p/ci"
    - "."
  volumes:
    - name: source
      emptyDir: {}
  initContainers:
    - name: clone-repo
      image: alpine/git
      command:
        - /bin/sh
        - -c
        - |
          echo "Clonando repositorio..."
          git clone https://gitlab.com/ahmedpuco03/mi-app-vulnerable.git /src
      volumeMounts:
        - name: source
          mountPath: /src
  volumeMounts:
    - name: source
      mountPath: /src