apiVersion: execution.securecodebox.io/v1
kind: Scan
metadata:
  generateName: "trivy-mi-app-"
  namespace: scb
  annotations:
    # --- Configuración de DefectDojo ---
    # Estas IDs deben coincidir con tu instancia de DefectDojo
    defectdojo.securecodebox.io/engagement-name: "SEMGREP"

    defectdojo.securecodebox.io/test-title: "Semgrep - Scan Automatizado"
    defectdojo.securecodebox.io/test-type: "Semgrep JSON Report"
    


    defectdojo.securecodebox.io/product-name: "Pruebas Funcionales2"
    defectdojo.securecodebox.io/engagement-type: "CI/CD"
    defectdojo.securecodebox.io/product-type-name: "USFQ-Apps"
    defectdojo.securecodebox.io/engagement-version: "v1.0.0"
    defectdojo.securecodebox.io/engagement-tags: "automated,daily"
    defectdojo.securecodebox.io/engagement-deduplicate-on-engagement: "true"
    
    
    # --- Cambios Específicos para Trivy ---
    defectdojo.securecodebox.io/retry: "5"
    defectdojo.securecodebox.io/retry-delay: "10"
    defectdojo.securecodebox.io/persistence-delay-seconds: "12"
    defectdojo.securecodebox.io/send-product-name: "true"
    defectdojo.securecodebox.io/auto-create: "true"
    defectdojo.securecodebox.io/send-engagement-name: "true"
    defectdojo.securecodebox.io/force-new-scan: "true"



spec:
  scanType: "semgrep"
  parameters:
    - "--config=p/ci"
    - "/src"
  volumes:
    - name: source
      emptyDir: {}
  initContainers:
    - name: clone-repo
      image: alpine/git
      command:
        - /bin/sh
        - -c
        - |
          git clone https://gitlab.com/ahmedpuco03/mi-app-vulnerable.git /src
      volumeMounts:
        - name: source
          mountPath: /src
  volumeMounts:
    - name: source
      mountPath: /src
