apiVersion: execution.securecodebox.io/v1
kind: Scan
metadata: # <-- Falta esta clave
  name: "semgrep-mi-app-vuln" # Nombre del escaneo en Kubernetes
  namespace: scb
  annotations:
    # ------- ANOTACIONES PARA USAR RECURSOS EXISTENTES -------
    # Usa el ID del Producto existente (reemplaza 9 por el ID real)
    defectdojo.securecodebox.io/product-id: "9"
    # Usa el ID del Engagement existente (reemplaza 50 por el ID real)
    defectdojo.securecodebox.io/engagement-id: "50"
    # Usa el ID del tipo de Test existente (reemplaza 170 por el ID real)
    defectdojo.securecodebox.io/test-type-id: "170"

    # ------- TEST (Opcional si usas test-type-id, pero puede mantenerse para claridad) -------
    defectdojo.securecodebox.io/test-title: "Análisis Semgrep CI"
    # Mantener 'test-type' puede ser redundante si usas 'test-type-id',
    # pero no debería causar problemas y puede ayudar en la identificación.
    defectdojo.securecodebox.io/test-type: "Semgrep JSON Report"

spec:
  scanType: "semgrep"
  parameters:
    - "--config=p/ci"   # reglas oficiales CI pipeline
    - "."               # escanea el repo clonado

  # ------- Volumen para clonar el repositorio -------
  volumes:
    - name: source
      emptyDir: {}

  initContainers:
    - name: clone-repo
      image: alpine/git
      command:
        - /bin/sh
        - -c
        - |
          echo "Clonando repositorio para Semgrep..."
          git clone https://gitlab.com/ahmedpuco03/mi-app-vulnerable.git       /src
      volumeMounts:
        - name: source
          mountPath: /src

  # ------- Montaje del código al escáner -------
  volumeMounts:
    - name: source
      mountPath: /src