apiVersion: execution.securecodebox.io/v1
kind: Scan
metadata:
  generateName: "semgrep-mi-app-"
  namespace: scb
  annotations:
    defectdojo.securecodebox.io/product-id: "8"
    defectdojo.securecodebox.io/engagement-id: "38"
    defectdojo.securecodebox.io/tool-configuration-id: "2"
    defectdojo.securecodebox.io/test-type-id: "93"
    defectdojo.securecodebox.io/test-title: "Semgrep CI Scan"
spec:
  scanType: semgrep
  parameters:
    - "--config=p/ci"
    - "/src"

  volumes:
    - name: source
      emptyDir: {}

  initContainers:
    - name: clone-repo
      image: alpine/git
      command:
        - /bin/sh
        - -c
        - |
          git clone https://gitlab.com/ahmedpuco03/mi-app-vulnerable.git /src
      volumeMounts:
        - name: source
          mountPath: /src

  volumeMounts:
    - name: source
      mountPath: /src
