apiVersion: execution.securecodebox.io/v1
kind: Scan
metadata:
  generateName: "trivy-mi-app-"
  namespace: scb
  annotations:
    # --- Configuración de DefectDojo ---
    # Estas IDs deben coincidir con tu instancia de DefectDojo
    defectdojo.securecodebox.io/product-id: "8"
    defectdojo.securecodebox.io/product-name: "mi-app-vulnerable1"
    defectdojo.securecodebox.io/product-type-name: "USFQ-Apps"
    defectdojo.securecodebox.io/tool-configuration-id: "2" # Asegúrate que este hook también sirva para Trivy
    defectdojo.securecodebox.io/engagement-id: "43"
    
    # --- Cambios Específicos para Trivy ---
    defectdojo.securecodebox.io/engagement.name: "pruebas_trivy" # Nombre del Engagement
    defectdojo.securecodebox.io/test-type: "Trivy Scan"      # ¡Importante! Tipo de Test para Trivy
spec:
  # --- Tipo de Escaneo ---
  scanType: "trivy-filesystem" # Usamos trivy-filesystem porque clonamos el repo primero
  
  # --- Parámetros de Trivy ---
  # Escanea el directorio montado en /src
  # Puedes añadir más parámetros de trivy aquí, ej: "--severity HIGH,CRITICAL"
  parameters:
    - "." 
  
  # --- Definición del Volumen ---
  # Esto es idéntico a tu ejemplo de semgrep
  volumes:
    - name: source
      emptyDir: {}
  
  # --- Contenedor de Inicialización (Git Clone) ---
  # Clona tu repositorio en el volumen 'source'
  initContainers:
    - name: clone-repo
      image: alpine/git
      command:
        - /bin/sh
        - -c
        - |
          echo "Clonando repositorio para Trivy..."
          git clone https://gitlab.com/ahmedpuco03/mi-app-vulnerable.git /src
      volumeMounts:
        - name: source
          mountPath: /src
          
  # --- Montura del Volumen en el Escáner ---
  # El escáner de Trivy montará el volumen 'source' en /src
  volumeMounts:
    - name: source
      mountPath: /src
